platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'MVVMGitHub' do
        pod 'GPUImage',                 '~> 0.1.7'
        pod 'FMDB',                     '~> 2.6.2'
        pod 'HMSegmentedControl',       '~> 1.5.2'
        pod 'MJExtension',              '~> 3.0.10'
        pod 'MBProgressHUD',            '~> 1.0.0'
        #pod 'Routable',                 '~> 0.2.0'
        pod 'DZNEmptyDataSet',          '~> 1.8.1'
        pod 'MJRefresh',                '~> 3.1.12'
        pod 'Reachability',             '~> 3.2'
        pod 'Aspects',                  '~> 1.4.1'
        pod 'SDCycleScrollView',        '~> 1.65'
        pod 'HMSegmentedControl',       '~> 1.5.2'
        pod 'OctoKit',                  '~> 0.5'
        pod 'YYKit',                    '~> 1.0.7'
        pod 'SAMKeychain',              '~> 1.5.2'
        pod 'IQKeyboardManager',        '~> 4.0.4'
        pod 'SDVersion',                '~> 3.6'
        pod 'MLeaksFinder',             '~> 0.2.1'
        pod 'WebViewJavascriptBridge',  '~> 5.0.5'
        pod 'CocoaSecurity',            '~> 1.2.4'
        pod 'Masonry',                  '~> 1.0.1'
        pod 'MMMarkdown',               '~> 0.5.5'
        pod 'UIView+Borders',           '~> 0.0.2'
        pod 'WMPageController',         '~> 2.2.1'
        pod 'JSONKit-NoWarning',        '~> 1.2'
        pod 'pop',                      '~> 1.0.9'
        pod 'DTCoreText',               '~> 1.6.20'
        pod 'OcticonsIOS'
end
